nameOverride: "product-service"
fullnameOverride: ""
replicaCount: 2

image:
  repository: product-service
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8083

service:
  type: ClusterIP
  port: 8083

config:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MONGO_URI: "mongodb://mongodb:27017/product_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  AUTH_JWKS_URI: "http://auth-service:8086/.well-known/jwks.json"

probes:
  path: /actuator/health
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70