server:
  port: 8085

spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI:http://localhost:8086/.well-known/jwks.json}
  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    username: order_svc
    password: order_svc
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
grpc:
  server:
    port: 9091
    security:
      enabled: true
      certificate-chain: file:${TLS_DIR:.secrets/dev/tls}/order-server.crt
      private-key: file:${TLS_DIR:.secrets/dev/tls}/order-server.key
      protocols: TLSv1.3
  client:
    inventory:
      address: 'static://localhost:9090'
      negotiation-type: TLS
      security:
        trust-cert-collection: file:${TLS_DIR:.secrets/dev/tls}/ca.crt
        client-auth-enabled: true
        certificate-chain: file:${TLS_DIR:.secrets/dev/tls}/order-client.crt
        private-key: file:${TLS_DIR:.secrets/dev/tls}/order-client.key
        protocols: TLSv1.3

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
