---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-db
  namespace: platform
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgAeExsVTggafGQBr0Ja+lt0OjzqiOaV27QRKLBg2hdwymlzh5RtIvlwroRWHZyPh76ZDXiXRlivIpENzqMVK0rUFoTar6xG99Zb77IXoBs4U5+4CRuPdpvDaWeh4lcGdGq1EBoqTl1QTU+q35j+0mTUtpk6AQHEqiqwbV+u5JHFOf+8PIm92KGYUMZXssuN8Im5aSDf6wPMsVfXWTnqwkpcS8kaBtlRdsvwVfzRzF/UPszwB1s8PFGwjrkNxkakeI3+u5BONkAW/CmhgkYkciCZzLiyOYFOUyej4A6QahAN91+yRIzXB3qXfPnzQd3f3OJBZTOFIazE5wzPVeWU6YnYcfs3KxOkLUVxJgbeNDrpv/bS4bMipFxo/HKI6ehRV43c0oM4Rrob3tgcS7Lp6D6Z3Ycp2mixEyf9QHvEm29QJDcN7XfCfD6Wjr0+5VO8e14L75qF0XEquZ7gCod0LKYJHgVWrjDYlc1XFl5nsbA9CIuoMuu7boLxSTSUqoWnn047HD36QLL2/OW4eafdKBpaPJod2JQPbO7+BBAUCh8JkSSETn5vVG3SoB2qEF/FtwshcCO+wERzE15nEaYUZI+BrhUrpNlKqfwUsMp2f7YjNNRozl0HF3kQiO3ATp/ybeH6rT5WuT4m2gTyKquL9txuPrqVfH3tiQ6YsAIFvq7Fju6UcyDGysfzOGMXxbTDnTPXICnx
    SPRING_DATASOURCE_USERNAME: AgCul1jPKnQcsav0Jb2KSvVcPrI5fPE6qXu2RHuqApOmYz1Fj42yrTIN5FMUIFkOniA73jv/MY6sZgbgCck5jkC571ry3X8Oof06UzCdoQB79aDuwLoXHyhErwHDCfah+dko8drBO0nn3mx/KUVbW3N9V1ne0SRbt1vmJ9AJ3hUI0Zvc4fUZL8I51GKZlf7wICHItrWO/W4OXEf9YYbsMEmXADQWj0Xdbyq4Uuq8ayTFhLsYLtgQtZkt74a2ix+CfLnKlLMQ4FnsrTPdrWzQSCBDii8rGydotS1n2XGGJpEDJksogZ+FQy9ytSUhVqWrxEzzQrGG+sgH1NbJvbUKkWeHGCHHCdYEk4EAPOyntrJn0ecrATpm6UYdsGRN3385Pd7N2XitNk7PgQ+OxcWE/xRwGXMJ6XmgbHtdIaQvMNfLvlgYZkMINxKGDgjUAR/Rr8bMnhj1IoZxg9yApgpyAS92LupZ+H7psoSe2gSRNABl/Jcd5JtJMd23OuM24EQr6aOg7rcZv3DF/he7riRe3oI1wLzCj84/B4lMVZF84Uq0BUpvUzfir4tKYqKn82dY9m2sXXxYG1UmCTMj+5IRi9SbZOWPC8huVejyh/svECiN2DHRFj04+8za5zT/jNIe/M0aLRAcIkh/06dErXtVemYB/AAVK33ipcsvOEbZcsw+sMIMM/G89SSI0PL4OREy2nzrOg2B
  template:
    metadata:
      name: auth-service-db
      namespace: platform
