---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-db
  namespace: platform
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgDEeJsnUUinjWX0vCagI4eS9zqjbK+ZH3r1d5NNmHq6Xa1307C/b4bU4sjjnLHU8Rmggiw+uO+bi6BB14XxGmCZz2hiD0EOkuq1kW2GYXvdVvVPtGtRKYnM0R1sN4ya2M7tCfdsl15WdFWJQ1MHc5PUx2q8dgssNQdXqlXemN4dQUlB+5DNgI7ZAiPPjX9PzOpMf+FiKWZLWrvSUMTZWPW1p1tDs0CNeXF17mRJwaJiJmzgKfshsPuAxSSTUPV4OCyT8hGapFruZ8CAyc/CxMqbVJv/fkkzigoF7M0oRbzmCkxsODksFNbh7+zsN9Vn62DzQqq+ipTgnKXN5Yh1nQ9F4pcih+qqRT9xhocwpugVbwcmP+8KRnfFoeadK9I9H3eWKSmuMhj7GQkDtxWlPkrOlX0lOd77ShXU3vJfbE8YojTtxxwPDDEGfDjCYo48KjHB49dnBBlf32gDRBQaGwhLJgZv77OTEJT2EZKc09hML4u0WH28ntuefnUfeEW0AjDfdrmsKmhtWw4NVQl0nE7IKRqpNkbn6+JJrVUQ452uhl4ntMZvojOoIQfkmnI/7DkJzEDWwEP688xoBUteMdcAXVG4Fue4xPSfVdsC/im4Ej2gxGcModdk9/AGzf0BmWVOdfBonYbGFMCCSR9F6hCEJ8Fn9hBEUc2fIhnMCP4k0xZQOYNtdEy8b0WFObsDL81gbLwa
    SPRING_DATASOURCE_USERNAME: AgCvDH2MaCMy/+OQZCAwtEVk/h3mM0HhuviOIAWELrP25plAYkgmJlKFA2A5bvdVI2gtrNhB4Cmf01iriuw4uFs7wNdkXJUrDqh6cwZQQK6oCH/fpLKqzi8tn1m1qQNUwXW7i5BFkl8DuvmCCleG4orB2o680MpbwSoWLP+duTOVu7yVv7PEe0He70cWKCcBDEysobqM941Ya23dptWRRMJ2QAJGdA+HqZAoZ1N7aVOEwDF1Hydrm9Sq3eiGe5w/I0EJANA9hRnKMhUiANw+C+hBas31pE2fwE1shAMvxML+QlZjWKS66+8uHrQN6NmFQxXq8oFFwDTu8eGzfEpcEsMfQz601msMUbdHc+fhnLy5i+vqPiTT7vnt4Md7JZohv7C1/zP+wAzDL3+PLsJy9pt/b5EcWpF9oMtsV0qkO5DUdXUeyL69RSzII7b0zkC10VuMqH7s1+IPJB981gFXCMwYuYtQDgaoh3y4XQowC7xfMfjJavhG4XXkSbEOq5hEq4W6DfjIuUqanK4+Ks2FkbACB1gaH8/P7aCohBRYZ8ytEQ55MJeGLbfwdbcF/00Zhd1oCpp/Ooo10H5X+rnoMe0lWH4sVH3ydyaWkIUZA/NGtMGiXyY/COM55UVIiSM1Z/uHAmKsjmuYmFi42Q8wn5q9JQDz4SF8IKDWhZQ/pW8LDHzOzkzw+vzbDqiBknL6lEgVu5P7
  template:
    metadata:
      name: auth-service-db
      namespace: platform
