---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inventory-service-db
  namespace: platform
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgB10u5X9g79K//bvBsWp/OS3Y9q4ghl13VG7Z/6pC3hUJjq1RKPF3wI3xUDlnfjwLbtJahDaQ5ddGI98AP7/fgalOAk/z/F2JJ14mnNPsZxGFu1qsGNdX4rlIDm02g1pTrM+3B7XqeOabZn0RZi+17lyUITBpNlaiRHso2Qs7bgXqYbTPtP2/n/YEqEKS0RyHNeCkFD7PYaUAecz/861o4gSMmx25Uh3dQtOuxwzwN7crfhMX3Js6CH/sxRlfDKpu1t1pu6JAzVEbuiHsKmx2whuDqiqCnjXLKG/RAsNQXvq6PkUrKiPxC9YJPzZZ7ex7WmxGeRWnlUvYK/oVUMTGNiWAoAEAIIzWFDUqkgGl9xxrx7uWWCMhOdxZeRQtJm5LPJ4PRcbLsk5Xq+4EuPrXgeahrlNf/5ski3ChKua9eJD53G2SLqETPTJbVj4poCDXRMKgXfqPMNsPsth/JD3NujRHw3yCO++U55Ki6lJA0EIlJ/k/XCj/vJ/7STFd+KYbCKzBUhPPsNiQjqHF2dZxv123T6qvzZWyGkZ+0Dhpy1EpowqrvEVzVYf6EFenpil0fBYjCh+28DRpioUGqv9YeTq/ZBc4LaVzQPPGVOeHzIIuu67uN+IHT6ZBh4qM2G0y85k9qyvu+72QDuIwpbO7m0IBbSs7IlEMUP/glonJhooXTkk5sVmeVGhD/e2U1zXO60fff2oPqtgET1nRd2
    SPRING_DATASOURCE_USERNAME: AgCUfQA3GckH+889mUAUSpMd1OSAfs/1OGYA62H1fIdskq/EUpSm5QvWzKtq8GLV1GLKGoerwisyEPedZB9pWuRwSopDnADCh2H6N8pJOWZRhzeJSlp8pDIb8Uv0av36kSCCGanFfNnbyM698G6cIcbXmPaL4WVVwbINOF89zHARTXMqG0GxLzBWWE0uFjDb7Yi3i9tal/GmLne3Gw07/xavRraZR27FoVN07cZvZM+5lq5RsGorbhU9lyOO23Ta2TTY1tZsRvmO9d4sbVIgMMGbLRtfKQKTWDwzDTGuXUlz+a7V8lRuvAe7RV3cEf0QMfRE2QuxFbIjBdXvdz4/8+D6aqZp7DjqXvVFdB/Eaf6HHXXduhr6wYzv7uv9sTbVuvUJoIumqaDv5ZWwVT/dMCTbgxlWwoU2h/r22Lb0CLtMsPMwiQv3OOQ4aH1lZqSFKIbtjGSXTgcfvi49MCITFEW8kY9yIH17M0hHOyyJWqQHJZscmvNSRZ3GIm0UvxRV3qKrXDdGT04+qsNCfvdIUUDmizRpmS1sRbVCqi7KVMEGcBTomGFHJ7Ei4PJF50EPhoeDjo1VUgqxVCJh5GBgz6DL8q2cmtcnIw+/Xq5PTesEak/JmC00QwxavYW5HVFvxAUrBmURtEBTDLvrzaqBR4CjMPM1LfxFGmNRpiu1eLDVidawCj56u1bNwpLz5kL3Qiu0mfjETlBUNV/CTg+z
  template:
    metadata:
      name: inventory-service-db
      namespace: platform
