---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inventory-service-db
  namespace: platform
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgAAHaZaNst7YC9DeX8oY+1GDDYDaO563zuY4BoDFXc+/XVs42BSkO4mH1gd9jX2aSYz+BhOI3yDll6Y3c/Yv76HoICQ8L36vjwrLkcAaTogsWZuhwH8WRCgmjfF1nAeSJ/Pet4kVMU7cECnTDm1n0ja9O/lkBGCCkqUoBnkDSkiKgAEOwqiqtRTM95wa7vwd+LBSW47eclV3aAkP6yQ+/qKhf42khWWwmUAzsEN8//OdLEqxh2vNMuTPAQEx544dZMxAr3NiYPg4o4jmts+MTBsArUNqbx0inyRkcJoDA1CFAxJpDZjJQChy/l9lzHPwxw6KpdDR4n1r27GflSlE4L9HXNh6urCUohyuoS1AeQIsdHtSDuP6iQ8Faba3FJykSJdzDtXp+M2jsTjVL4tlWPTuBKq9hOAineck2pHpCHjcIrBPufmNKB1FLIY8YHZpJGoJ84YXEjsVQbYM2DJBD36ylUNWSu2bcCQehEzFd1Zh2iRSLgukrK7njqo64wb3kBxbZuV75uY0ekrU9gbwiDWSGUDWJ+K9+rV+8boH0+znKQCP6KPIR2ZJ+pd2ZOcIwXWZfEp83jozcNa72vIA/xxevT8Iwpo8fHsVBLMO76oI8OYlB8Ge53Qkp8Y4g6yRb4/NOz7ykahqMaWpaiEHiMMoSt6y2mWG2uOOLZl4YlFK8YhAFPmpr2fuVImTTMuGQq8+FtCXIwMIik5AoAv
    SPRING_DATASOURCE_USERNAME: AgCB3A/8Zz/hp84JV1nAxFf4Z0FSWecVfc1GUxbtpX261wWKfh2XucNjTZyBAY/uVBWjFgvshmFQ+PE8t9BXkI/xF2qgaRb3U6SjxDx4pdS29Ln8sCDuTdcYbbtn4OFGX/ZIiweHgNSI2fzSKhqxEMaoSFIylCzsekmurRgVFGXIR2cIUBqRdKHx6KtdwSLYk4quc9Xv7bqYkYE89asIF0mNoWQHx45Z28P7lXhXSLRO8SwqfYoJZb/rjQ1uf/9MeVDQD+w9dVcKFguuMvkFp7hrVykZsw76lcB5aJknOXt9jWA9F6Sgg2723n2QisBQLbe2/2xtiK0sIeiDseGM9J1hTCsVVyhHsQ1OQbNrR2ja7H7ZFgaunXoWjw0zntNr02m+JEo3KWaA9YGvF2FhIldDdr5ycSRK0CkdHlNVAkuU3ow+ZoBJios6qDf6H4ijCoHm0jJ0qZ9iFX5KbMYOFrnJ9pdZ9eQ2DchJztpdviog9Udsp1uphlx2YhzRkDLHBLEcpHiXfPzUCy8UUBEmKplmKuzzjMN7YKVzTwCWLmFDqvK7WMbtRuVHs5Qgm0Qk7XdddSrvXVlrjXWnkU2fnsYvUB+aEtuZ6I6bVWzVrBrDh9phmzpimCcpfgRpE1zFPrYOJKj3mM5BzQ/Q6y/ZgG0wXSkxqWgv4plpnwFh/6P7HAoniKLKlApSRqXdky7Yy6oZS+534mOOYJUMX6Fe
  template:
    metadata:
      name: inventory-service-db
      namespace: platform
