---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: order-service-db
  namespace: platform
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgCFjRb0UwiyTD+sq1r0fAUB//8csGXXSo4LHxZpZL2bXtksvkvFMPvzRaSANeJyR44lf5PIiY2nLn5OSATlAffHKfrxWbBTX8hyw1JXKJzr4KLSDQ49kxA5xprZeB6Lmgy92Y0lbr09knXlR7QR89+KPMYULcMlfSU0RMDh9+eVpI+4SOnUSvN2rbFesMWrckcSw6Sf+TpOpXCUtFuGzK2AZvEm4RiiEda94MIxMkDBrKCg+0jGkOsAuoZy3wdwCE4qvPMAVckJKW0Zt8kArUrs+0fx5uukn7IB/7quRafjRHvJZjZyOZShymEpj254SMLVx7U61DGyDjp66iYNSFwbmqZztdCZUFBQyia4jRfnttvlDJs2omUkr+eO5qd9Y75XuyCZ3IXLXXDkO5Ktu3hQ7E6703QV3XLeETJgPOLHPeEIZ2NEk9JFnB3hgL7BlCRpqQcI/QZFiKhyuspn4NE0LQ/5hzOr1DaH0mbQHeBmLaGV1KXy21eaQOy1w8142s+CIENcTXuw2/GMFfTymn4eLv8/naBh3WyW3EF3t8w6Gf8xOVtmy5SIDl8T2QwMy0yRmkQDZbJCR/F0D2XS/vNW/pn4VszAgPN9f0rcPfN2mWZDpxTHOjypApeSwCNncCFzuY/pRl4IJKmFyTfDV/+s12AdMgfMP8g9LBP2udgKWZ1fGcqF/RRVYzZCrpT2mbx+JoKGiR771o0=
    SPRING_DATASOURCE_USERNAME: AgA9hFZriMwwM0QXYy01bygkCCQ3nDGBJ5aMzezJUzBkKIW/YyiqwHv1ey/aNKpBU3m+xB5vPyPHOO8foSUVDCVrJQ30sRDCawCv6TfZUV4sykdMh4mge0E98R5AJHM0Ej/cz1WOj8XcgSVPK7LOToZtFoXRqUfewdPVtXo/Y5kEDdhnfOCibErgybItG7QDZfB89KDMGJVIQvSfPftFk2klc3hgBizQKuUBo+rdSUOhUJ+eUFCw8IUqd9btIJ9VML9LvWuakvRAcWahFLOg3CFc3+gc0UyFIAi+bth69/4ymkZt3N18QncnaE+lwwmaIAQBkA7GKKTUyq/Bl1FMl9Cz3z5pxuJH4VHS6c/wNu0eo1779cviaaPTpq7SrS8zJtFJOEpYkH3/hoN5f8w08lySkFMO2UrbPP/KUnn/+xA3tu2BpCWu1z218dXz9TXfCNMqCrxPvQhj7HBhdxP9p5Yq8dMQROC+UFzv2DTbyP/1o3415UUa0YSvVbZoLS5tuGpf2lozh1XbjyjtJvVKGv2Vc24hGGXrXgbMvo5XCWQNrTDiBG7+YYmUVVWt8caOIbIz3yKrHtX0dW2sQrOyY1kFOTAs7CyefjvluAqYNbDIGW2zmBtziyQo/P6FL/Rq7Zds1l2ecoyrBwpBXv1g+s/b6og9rankqE/y5qxEdcwxnhjkpDnZNAs0HbC/IgUqBqFuKV26j+A5DTo=
  template:
    metadata:
      name: order-service-db
      namespace: platform
