---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: order-service-db
  namespace: platform
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgBmD3FC76nfFQDDKuAJs3VVwdXIZqJGUr3Izx9QAXJkiT+8e0hXT7HH/Mt5EHChk3ZS6iqmT4cLDjbJXIQQ4DmoY/ZPa8ye8jikIhZhZE94Qb8MdUJy4Z2puVOIOvA+SxpdiF44emiMI5zAHLSlP6M54Od6yzQj1KrKDbKnvNkP3nD2Ke59DDOnW3tWBVv22jsZaHvUd3hUyWpqUQiHKUyLPaPvGJ/7Eie1Xu8FYpJjXF3YpJ5GnwDnuAFpKXegyM21pIjmDN3nyIjABwnaqURI9l4+mIsDSeLo/d2jynmpI7QjNtUMJmx9UEwFppxkv4gMDC4RwbHAPfNrBSIv60ONoiPEF/VleHFtZ/kK3VhWRcUrmFYU88xIeOzpoekEbxJL7YJmMIcMRlqDhuDRrAkXvqrXwDciR1y7iLH0LwKzE3Yveyh23EqpTjY6BEDNIPsut21wdmIsGug9oFNMHk1ldxY8zMKudhe4AP+WC+ckHiiaEtolvH6GOC8wSRbE2IIsWe4lX+EYttdLdRcgW1Zf8O7sKG+aq6TzzaZl8j9aTn2I5Eq3AavEutJZa/3xdGv8tzvS9+VT3jz8DjB+rb0dtvRHSUC57+RX540KdFCbO+Yn/PU3mASk4om8DLCXFMP4E69MjfxR+U2Ke+dgXA+e78ib2g8HQOLarptKOC6fl89Le9qjrHkF1DXxjf+4hf+pWtVpTjCXGsg=
    SPRING_DATASOURCE_USERNAME: AgC5+Z9ynsVWCNix4TKHpdjZO+0bFDhaCTzyJRV1clzl7HPOAre835tPOqYcQEKC2uzsvbIfXzTqjv5WDwkkMpPt0ShZxQRiFrOs746woI96BAelAOGU4xTLcpcMR5tHWzPvDuVaU0K1mOAAVqfFLzOE/VLHqaTbDd23lP/IPr01/Zv297OZjuqOboqL3JYHhKE6JJikjLrMJ7aooPlLHp3Ps6Z92z86CT3E6ag6CV0j2vuNXPc7zDRrJjqqqCAZ1RjTHxtkd7+J4h453DRq+L3SdKN0nsj2Y3W/cLld0Um7NAbhOVQY40UwkFhLaH+0X7Wnvq1gTJYMDCQ2nsLNk3kLBV1QsrgRiqXqcQbfPJtcn2BlU3SFujv2wAIB0mwqHZhWQ230OEGUxL5AVvGah+puZzmWRvgzFKf4usrhxrl7TVHH8/ur8vY/q9l1izaH5vqf6kZby/5C/MzV1q4554LZkUjEaXWVunRxwTS3zf+EDYhhNEcO+mTIF950QIpXknkHbgGa54RmUuIBLywKWFQdI2nFJOJxrWPp3fzJv7EV/v0vWoWqHA0+pWD8twMjPs7gQjK5r+Wy6PYP3SRO3xAeXejaOIUypB5Nlv54B+lBNbT4fXDh54Twj6WOztpEHHWWDs3AwPkCU44Sm+N6BpAsJ7SeCMnT502ZUzpgXBzJl1I6MetQDuslr6lsY5EKiSTNhB6/7X4FxuM=
  template:
    metadata:
      name: order-service-db
      namespace: platform
