---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-service-db
  namespace: platform
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgCdm1UVsUHIByjIvy50Qb2DF2C5VsegVA5mygE5gUQ2TuFDGww/5PsqAH153a8lXy2ULklWr7S+JDWOGHOs6SoBHrlBQNRMmmu8dGeFHsBt+EWCJYC6us5cncTFfjPF87eDO7WXLSIWPQdgB/Lkq2qd6IOVodRgrmtLqUVMacTfjbnd8W8Eq8xjRZ/vYQOG2GDqPYq1Btg1cidAskCA3xtmsn3AcMXddi7j5uELczCIOtITJ39athIxQL23Ixlsh2qr8yHO9mGFNjJjzbRN1gld/zuJTfLjBpbnLoTlDAnZqfei5f3fcc19EyVfTSW1UEe9vkMOSbA90qEvyOhnUtR2n4a/zULWyu6Gco7MreQAb/nyT2GueeX/KoLml8tQhIkBh9Vy6IIu7ce+03RnenrANUp97IHq27crNV2E4J2153lOPyYfY9uSy53IcVOHDLIT52eRK2cpALwnjcKGBZsSg5WD3cG0d4aeoEgPIvUnq2KAJcJ6FMGv4OO654chNZAt1qkN2bA8yhPpStRiJBZy0NNfY2q2V1WOJUG1QkQWqIFcfuke02F43O3ikKTW7rIxT+KHMyWgiwPfYEesj++lkutp5K1J1ecmWnXifCyo/c08LVARmOcKtpEmIeLlIpNjkXsxeOkfRkTF8jUI4CWtSTde/liwCIHI+CHzwm2Ip82MXrwM+otvxBzAlLlgAjYvx/EMIOAMkA==
    SPRING_DATASOURCE_USERNAME: AgCww2rogwFTQpQUIHEXGtLnkGXvwBYYXjnTyxrHMUAs2hWUyqBxPVGy6h7ZybboXPPWBi/7vkOtZNeVmea9omgDMx9AWwIKqjrFh0iEDpJHrHFuqERmBFlRaUuPAACyAOlme7NB/9sxU8Oce7+GsKhhjxdZZNHHtXi0fgy/FnkpsQoVwJwg5OLJla+2TmWqlisIGXVnRiEFcaCG65ABuvUVQtcFtXNxtl318gLMRLpWX+qARkT8dBYYBfrM6ZKue9pfb2/Fj2IcsK4E7zMo7Ph+6QfFw2jB+Dlikwhk27PqH5l7x/8V9bOgsLdPh8+zfIZGlDBixVYXJoNn/xUL5ZIRL4N5BL9u/4g0GoRdMe+Lxro6tjDzQn0UDFCSgmS3f3x1Rod4QR8TPTGO5CKnQO2Tohr2hl3NgQYjeriZYnlOmubUV+mYDuOtZGBImOSyZ2dFxUc3UH2E3A6pcO7ytmYIu2xhioRg0cTfuTVmVAPcq2A8F68UHWaYIFDwsaawKSW5b0y0Osc6OHtztHqEKm6c7IMR0iJ0EnbP6QzfXSCH6//k8KOhQYpjR0LdURHkAhmoKWIjubhUCFywLtMZHe5A0sHE8eKETH4HmBUmjJfM1mUJvFFLzReSEuEnaBHlli+nencFomMXcAQ9IyOJyLyh57nWSXL/1g7myiP9/6jVQo2+5bRFUoZpqyOZPls3z6Ty2UTYou8lKA==
  template:
    metadata:
      name: user-service-db
      namespace: platform
