---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-service-db
  namespace: platform
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgCuCHAm7Z9v04lwNPgHwCcAY66cfzBl/1tfujDLSl9lgMs5j+2l2/geYt68SwJDKF59e3JNCXA5W8jTE+HhugH9LqKE8tV2UnjdAgw5ubUStDHobijl0b1zJpKYVfry9KamilzSMR7Z3WqtnYhNRxwUmgut5ilGyqTFC/GnFl5nSr30yfIF0pNztba822ZQTv7axxZApu8er0qlyBqCxYf71I5yonh/kaWL25+n6+FyIjjQSOVNnl2CBPsGVMWcZn1rLABcyjX7k+446A7ZT/pJ5vR+PafWKVfvrZFwh0G2i5+RdwlZyTV331I3nUbRF6x5kg79khm5Sj9S5YR3AjtS+aS3p3Ix7SLkwl1pWAdlUpKVJl/k3jWlIWySqkH/zOZGuZo29inkCOQOvwEVahzZtwKQ5NtkGMt6iD7Ufr8G9HU3JRzmaMyFeDLZXsIb7kW6RBTydNXOHaGmpoSfuka/GyjBnpryNbec7lAds550S6zfVDEveXjv5nsDPWEW8lZxNdec5RuL3CeL64UNXfX/zxpnfnUAc3ufwLt5IS0Ps5juT/byRp3RIzxM2VGlmTcdVEJsr8tdSDrEcs8HokqZ05oFYxKu6XhSY5JnzCGVXEIcVbGtpwEPjOVYXGOCYq5UsY8heGsALvzsMxvigQa5rdJwArrlxbqEV7nF4vsihKIFI3u/CqY4XkdV8CWSZX8c2pBiuE3UNQ==
    SPRING_DATASOURCE_USERNAME: AgCS602iaNANuWAm3wGp74ztvbdqXjAwy+1YGyHxCWvQdVdrLpKuJPkB42zXXLPtIZqgPT+Vbgwo3Uh0U1u1t6qY9Vb/S/ZbLcZWAzszSoryyEsMTQFctAOmREGXgW3ca1t71E6dMJDexHYJFFJ/KfXUBf5eK6S1tfK+AhYZ2tLqBwktp//Eu9xumd4ywDkWto3eaKN3Qkkw4QVzLAvZFqtygelp4xOJ1xU/KhGV/fwo4QQjlLQYShuFM47kQLg9pSHTM0BMOekYDvv3ShTS+C8Qtv/Pu8jQlLH13eViOKP8i36ae5bxAfwMK3JugUBkHR9vCndChqT07iex9Sx4esB5AmPxQ7l02CO0CJvtaEaGQtfUUWqQq1hBNrTKAFw9NAgmzl60P8hnyQdUMEMH7JfPVlu4ypMFu+4EMSQUwXmTf8+K83BR46uhjtF23qHsBpTa/+nTzp0PbZxqD91bdv2ZRTfBBvT5/dmzmTVI3tENd35BxphzQ98oRdNzP1aswkxlAPC2mOm0SQEbv0sDozBOpstJrpshOAEVoLNszxG6C3iGwbDAxW20YXhtRs25beZFwwI2iBqp7Si1DONlG6prhK7eEB4d4Jx/AGllgTlTdL3cWQx17/zOzR4CpBDt82CmHhE0J8Puzn0wlINVIAnacK7fgnjDRgaD1ENNYU6SSRcx6HJZvaHp48pjCh3zCpwxjLCUFPxV8w==
  template:
    metadata:
      name: user-service-db
      namespace: platform
